[project]
name = "example"
version = "0.1.0"
description = ""
authors = [
    {name = "roey-e"},
]
dependencies = []
requires-python = ">=3.7"
license = {text = ""}
[tool.pdm]

[build-system]
requires = ["setuptools<61,>=42"]
build-backend = "setuptools.build_meta"
