[project]
name = "example"
version = "0.1.0"
description = ""
authors = [
    {name = "roey-e"},
]
dependencies = []
requires-python = ">=3.7"
license = {text = ""}
[tool.pdm]
build = "build.py"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
